[build]
  command = """
    echo "export const environment = {
      production: true,
      emailJsServiceId: '$EMAILJS_SERVICE_ID',
      emailJsTemplateId: '$EMAILJS_TEMPLATE_ID',
      emailJsPublicKey: '$EMAILJS_PUBLIC_KEY'
    };" > src/environments/environments.private.ts &&
    ng build --configuration production
  """
  publish = "dist/giulia-spanu-website/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/angular-runtime"
  inputs = {}